# Generated by Django 4.2.6 on 2024-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cennosti', models.TextField(default='ICL это: Открытость, доверие, инновации')),
                ('structure', models.TextField(default='Крупнейшая ИТ-компания России')),
                ('history', models.TextField(default='Основана в: 1991 году одним из крупнейших производителей вычислительных комплексов (ЭВМ) в СССР Казанским производственным объединением вычислительных систем (КПО ВС) и крупнейшим производителем компьютеров Великобритании International Computers Limited (ICL) было создано советско-британское совместное предприятие «ICL-КПО ВС», зарегистрированное 2 июля 1991 года в Министерстве финансов РСФСР.')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Раздел инструкций')),
                ('link_1_href', models.TextField(default='#')),
                ('link_1_view', models.TextField(default='Ссылка')),
                ('link_2_href', models.TextField(default='#')),
                ('link_2_view', models.TextField(default='Ссылка')),
                ('link_3_href', models.TextField(default='#')),
                ('link_3_view', models.TextField(default='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='LearningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Раздел')),
                ('link_1_href', models.TextField(default='#')),
                ('link_1_view', models.TextField(default='Ссылка')),
                ('link_2_href', models.TextField(default='#')),
                ('link_2_view', models.TextField(default='Ссылка')),
                ('link_3_href', models.TextField(default='#')),
                ('link_3_view', models.TextField(default='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='LinksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Раздел')),
                ('link_1_href', models.TextField(default='#')),
                ('link_1_view', models.TextField(default='Ссылка')),
                ('link_2_href', models.TextField(default='#')),
                ('link_2_view', models.TextField(default='Ссылка')),
                ('link_3_href', models.TextField(default='#')),
                ('link_3_view', models.TextField(default='Ссылка')),
            ],
        ),
    ]
